---
start_time: '2025-02-05T08:00:00'
caltopo_map_id: 8QDFJ7P
runner_name: Aaron
route_name: Route
route_distance: 220.8
race_name: TWOT 200
aid_stations:
  - name: 01 TWOT Lot
    mile_mark: 27.6
  - name: 02 TWOT Lot
    mile_mark: 55.2
  - name: 03 TWOT Lot
    mile_mark: 82.8
  - name: 04 TWOT Lot
    mile_mark: 110.4
  - name: 05 TWOT Lot
    mile_mark: 138.0
  - name: 06 TWOT Lot
    mile_mark: 165.6
  - name: 07 TWOT Lot
    mile_mark: 193.2
