start_time: '2024-02-25T08:00:00' 
garmin_api_token: 8E22F454
caltopo_map_id: U5P1F
caltopo_session_id: 7C40CE0B00386DDF9B41D19616729077
tracker_marker_name: Aaron
route_name: Route
aid_stations:
  - name: 1 Air Down Lot
    mile_mark: 23.3
  - name: 2 Kimball's Kitchen
    mile_mark: 34.6
  - name: 3 Kitty Hawk
    mile_mark: 46.7
  - name: 4 Coquina Beach
    mile_mark: 65
  - name: 5 Pea Island
    mile_mark: 74
  - name: 6 Rodanthe
    mile_mark: 82.8
  - name: 7 Ramp 30
    mile_mark: 93.6
  - name: 8 Lighthouse
    mile_mark: 107.3
