---
version: '3'
services:
  ultra_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    image: ultra_tracker:latest
    container_name: ultra-tracker
    ports:
      - 8080:8080
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /proj/ultra_tracker/application:/app
