---
services:
  ultra_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    image: ultra_tracker:latest
    #    logging:
    #      driver: none
    container_name: ultra-tracker
    ports:
      - '80:8080'
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - '/proj/ultra_tracker/application:/app'
