---
services:
  ultra_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    image: ultra_tracker:latest
    logging:
      driver: none
    container_name: ultra-tracker
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres:18
    container_name: ultra-tracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_RO_USER: ${POSTGRES_RO_USER}
      POSTGRES_RO_PASSWORD: ${POSTGRES_RO_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ultra-tracker-postgres-data:/var/lib/postgresql
      - ./postgres_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  grafana:
    image: grafana/grafana:latest
    container_name: ultra-tracker-grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning/
      - ultra-tracker-grafana-data:/var/lib/grafana
    user: '1000'
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_RO_USER}
      POSTGRES_PASSWORD: ${POSTGRES_RO_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_USERS_ALLOW_SIGN_UP: false
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_USERS_DEFAULT_THEME: dark
      GF_DASHBOARDS_JSON_ENABLED: true

volumes:
  ultra-tracker-postgres-data:
  ultra-tracker-grafana-data:
