start_time: '2024-02-19T08:00:00' 
garmin_api_token: XXXXXXXX
caltopo_map_id: XXXXX
caltopo_session_id: XXXXXXXXXXXXXX
tracker_marker_name: Aaron # TODO
route_name: Route
# TODO validate these
aid_stations:
  - name: 1 First AS
    mile_mark: 10.3
  - name: 2 Second AS
    mile_mark: 15.9
