{
 "title": "Interactive Running Log Explorer",
 "tags": [
  "running",
  "postgres"
 ],
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "1d",
 "panels": [
  { "title": "Running Stats", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Running Log Summary" } },
  {
   "title": "Activities",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"Start Time\",\n  duration_min AS \"Duration\",\n  distance_mi  AS \"Distance\",\n  to_char(\n    make_interval(\n      secs => ROUND( (duration_min::numeric * 60)\n                     / NULLIF(distance_mi::numeric, 0) )\n    ),\n    'MI\"''\"SS\"\"'\n  )  AS \"Pace\",\n  average_hr_bpm AS \"Avg HR\",\n  average_temp_f AS \"Avg Temp\",\n  gain_ft  AS \"Gain\",\n  notes AS \"Notes\"\nFROM activities\nWHERE $__timeFilter(start_time)\nORDER BY start_time DESC;\n"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(duration_min)::numeric\nFROM activities\nWHERE $__timeFilter(start_time);\n"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(distance_mi)::numeric\nFROM activities\nWHERE $__timeFilter(start_time);\n"
    }
   ]
  },
  {
   "title": "Avg HR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(average_hr_bpm)\nFROM activities\nWHERE $__timeFilter(start_time);\n"
    }
   ]
  },
  {
   "title": "Locations",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT start_time, latitude, longitude FROM activities WHERE $__timeFilter(start_time);"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(distance_mi)::numeric\nFROM activities\nWHERE $__timeFilter(start_time);\n"
    }
   ]
  },
  {
   "title": "Gain",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(gain_ft)::numeric\nFROM activities\nWHERE $__timeFilter(start_time);\n"
    }
   ]
  },
  {
   "title": "Pace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(\n    make_interval(secs => ROUND(\n      (SUM(duration_min)::numeric * 60)\n      / NULLIF(SUM(distance_mi)::numeric, 0)\n    )),\n    'MI\"''\"SS\"\\\"\"'\n  ) AS avg_pace\nFROM activities\nWHERE $__timeFilter(start_time);\n"
    }
   ]
  },
  {
   "title": "Gain per Mile",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ft/mi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(gain_ft)/SUM(distance_mi) as gain_per_mi\nFROM activities\nWHERE $__timeFilter(start_time);\n"
    }
   ]
  },
  {
   "title": "Cumulative Totals",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "rawSql": "SELECT start_time AS time, \n  SUM(gain_ft) OVER (ORDER BY start_time) AS \"Gain\",\n  SUM(distance_mi) OVER (ORDER BY start_time) AS \"Distance\"\nFROM activities ORDER BY start_time;"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "rawSql": "SELECT start_time AS time, gain_ft as \"Gain\", distance_mi as \"Distance\" FROM activities ORDER BY start_time;"
    }
   ]
  },
  {
   "title": "Average HR",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "rawSql": "SELECT start_time AS time, average_hr_bpm as \"Average HR\" FROM activities ORDER BY start_time;"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT start_time AS time, average_temp_f as \"Average Temp\" FROM activities ORDER BY start_time;"
    }
   ]
  },
  {
   "title": "Annual Totals",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  EXTRACT(YEAR FROM (a.start_time AT TIME ZONE 'America/New_York'))::int AS Year,\n  COALESCE(SUM(a.distance_mi), 0)::numeric(12,2)  AS \"Distance\",\n  COALESCE(SUM(a.duration_min), 0)::numeric(12,2) AS \"Duration\",\n  COALESCE(SUM(a.gain_ft), 0)                     AS \"Gain\"\nFROM activities a\nGROUP BY year\nORDER BY year DESC;\n"
    }
   ]
  }
 ]
}