{
 "title": "Testing",
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "map_url",
    "label": "Map URL",
    "query": {
     "query": "SELECT map_url FROM race LIMIT 1;"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "running-log",
     "rawSql": "SELECT to_char(start_time, 'FMMM/FMDD FMHH12:MI AM') FROM race;"
    }
   ]
  },
  {
   "title": "Elapsed Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "running-log",
     "rawSql": "SELECT (duration_min * 60) FROM activities ORDER BY start_time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Mile Mark",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "running-log", "rawSql": "SELECT mile_mark FROM runners;" }
   ]
  },
  {
   "title": "Pings Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "running-log", "rawSql": "SELECT COUNT(*) FROM pings;" }
   ]
  },
  { "title": "Course", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Course Stuff",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "ultra-tracker",
     "rawSql": "SELECT\n    name,\n    display_name,\n    mile_mark,\n    'leg' AS type,\n    arrival_time,\n    departure_time,\n    estimated_arrival_time,\n    estimated_departure_time,\n    distance,\n    gain,\n    loss,\n    is_passed\nFROM legs\n\nUNION ALL\n\nSELECT\n    name,\n    display_name,\n    mile_mark,\n    'aid_station' AS type,\n    arrival_time,\n    departure_time,\n    estimated_arrival_time,\n    estimated_departure_time,\n    NULL::DOUBLE PRECISION AS distance,\n    NULL::DOUBLE PRECISION AS gain,\n    NULL::DOUBLE PRECISION AS loss,\n    NULL::BOOLEAN AS is_passed\nFROM aidstations\n\nORDER BY mile_mark;"
    }
   ]
  },
  { "title": "Map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "text",
   "gridPos": { "h": 17, "w": 19, "x": 0, "y": 27 },
   "options": {
    "content": "<iframe\n  src=\"${map_url}\"\n  width=\"100%\"\n  height=\"99%\"\n  frameborder=\"0\">\n</iframe>"
   }
  }
 ]
}